-- CreateTable
CREATE TABLE "Contract" (
    "id" SERIAL NOT NULL,
    "nrInst" TEXT NOT NULL,
    "nrAgencia" TEXT NOT NULL,
    "cdClient" TEXT NOT NULL,
    "nmClient" TEXT NOT NULL,
    "nrCpfCnpj" TEXT NOT NULL,
    "nrContrato" TEXT NOT NULL,
    "dtContrato" TIMESTAMP(3) NOT NULL,
    "qtPrestacoes" TEXT NOT NULL,
    "vlTotal" TEXT NOT NULL,
    "cdProduto" TEXT NOT NULL,
    "dsProduto" TEXT NOT NULL,
    "cdCarteira" TEXT NOT NULL,
    "dsCarteira" TEXT NOT NULL,
    "nrProposta" TEXT NOT NULL,
    "nrPresta" TEXT NOT NULL,
    "tpPresta" TEXT NOT NULL,
    "nrSeqPre" TEXT NOT NULL,
    "dtVctPre" TIMESTAMP(3) NOT NULL,
    "vlPresta" TEXT NOT NULL,
    "vlMora" TEXT NOT NULL,
    "vlMulta" TEXT NOT NULL,
    "vlOutAcr" TEXT NOT NULL,
    "vlIof" TEXT NOT NULL,
    "vlDescon" TEXT NOT NULL,
    "vlAtual" TEXT NOT NULL,
    "idSituac" TEXT NOT NULL,
    "idSitVen" TEXT NOT NULL,
    "vlMovimento" BOOLEAN NOT NULL,
    "nrTypeDocument" TEXT NOT NULL,
    "vlInstallmentValue" BOOLEAN NOT NULL,

    CONSTRAINT "Contract_pkey" PRIMARY KEY ("id")
);
