-- CreateTable
CREATE TABLE "contratos" (
    "id" SERIAL NOT NULL,
    "nrInst" INTEGER NOT NULL,
    "nrAgencia" INTEGER NOT NULL,
    "cdClient" INTEGER NOT NULL,
    "nmClient" TEXT NOT NULL,
    "nrCpfCnpj" TEXT NOT NULL,
    "nrContrato" INTEGER NOT NULL,
    "dtContrato" TIMESTAMP(3) NOT NULL,
    "qtPrestacoes" INTEGER NOT NULL,
    "vlTotal" DOUBLE PRECISION NOT NULL,
    "cdProduto" INTEGER NOT NULL,
    "dsProduto" TEXT NOT NULL,
    "cdCarteira" INTEGER NOT NULL,
    "dsCarteira" TEXT NOT NULL,
    "nrProposta" INTEGER NOT NULL,
    "nrPresta" INTEGER NOT NULL,
    "tpPresta" TEXT NOT NULL,
    "nrSeqPre" INTEGER NOT NULL,
    "dtVctPre" TIMESTAMP(3) NOT NULL,
    "vlPresta" DOUBLE PRECISION NOT NULL,
    "vlMora" DOUBLE PRECISION NOT NULL,
    "vlMulta" DOUBLE PRECISION NOT NULL,
    "vlOutAcr" DOUBLE PRECISION NOT NULL,
    "vlIof" DOUBLE PRECISION NOT NULL,
    "vlDescon" DOUBLE PRECISION NOT NULL,
    "vlAtual" DOUBLE PRECISION NOT NULL,
    "idSituac" TEXT NOT NULL,
    "idSitVen" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "contratos_pkey" PRIMARY KEY ("id")
);
